ALTER TABLE withholding_entries
  ADD COLUMN IF NOT EXISTS tax_deducted_paisa BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS document_id TEXT,
  ADD COLUMN IF NOT EXISTS review_status TEXT NOT NULL DEFAULT 'NOT_STARTED';
